# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_auto_20170407_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='first_name',
            field=models.CharField(blank=True, help_text=b'The users first name (Christian name)', max_length=254),
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='last_name',
            field=models.CharField(blank=True, help_text=b'The users second name (sir name)', max_length=254),
        ),
    ]
